version: '3.9'
services:
  # This is the frontend, you can remove it if you want
  swetrix:
    image: swetrix/swetrix-fe:latest
    restart: always
    depends_on:
      - swetrix-api
    ports:
      - '80:80'
    environment:
      - API_URL=http://localhost:8080/api/
  swetrix-api:
    image: swetrix/swetrix-api:latest
    restart: always
    ports:
      - '8080:5005'
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mariadb
      - CLICKHOUSE_HOST=http://clickhouse
    links:
      - 'redis'
      - 'mariadb'
      - 'clickhouse'
    depends_on:
      - 'redis'
      - 'mariadb'
      - 'clickhouse'
  redis:
    image: redis:alpine
    restart: always
    environment:
      - REDIS_PASSWORD=password
  #   volumes:
  #     - '/opt/redis-volume:/data'
  mariadb:
    image: linuxserver/mariadb:alpine
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=analytics
      - MYSQL_USER=swetrix
      - MYSQL_PASSWORD=password
  #   volumes:
  #    - '/opt/mysql-volume:/var/lib/mysql'
  clickhouse:
    image: yandex/clickhouse-server:latest-alpine
    environment:
      - CLICKHOUSE_DB=analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    restart: always
    #   volumes:
    #    - '/opt/clickhouse-volume:/var/lib/clickhouse'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
