version: '3.9'
services:
  # This is the frontend, you can remove it if you want
  swetrix:
    image: swetrix/swetrix-fe:2.0.0
    restart: always
    depends_on:
      - swetrix-api
    ports:
      - '80:80'
    environment:
      - API_URL=http://localhost:8080/
      - REACT_APP_AIAPI_URL=https://aiapi.swetrix.com/
      - REACT_APP_SELFHOSTED=true

  # This is the analytics API
  swetrix-api:
    image: swetrix/swetrix-api:2.0.0
    restart: always
    ports:
      - '8080:5005'
    environment:
      - JWT_ACCESS_TOKEN_SECRET=jwt-access-token-secret
      - JWT_REFRESH_TOKEN_SECRET=jwt-refresh-token-secret
      - REDIS_HOST=redis
      - CLICKHOUSE_HOST=http://localhost
      - API_ORIGINS=
      - EMAIL=test@test.com
      - PASSWORD=12345678
    links:
      - 'redis'
      - 'clickhouse'
    depends_on:
      - 'redis'
      - 'clickhouse'
  redis:
    image: redis:7.0.11-alpine
    restart: always
    environment:
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_PASSWORD=password
    # ports:
    #   - 6379:6379
  #   volumes:
  #     - '/opt/redis-volume:/data'
  clickhouse:
    image: clickhouse/clickhouse-server:23.4.2.11-alpine
    environment:
      - CLICKHOUSE_DATABASE=analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_PASSWORD=
    # ports:
    #   - 8123:8123
    restart: always
    volumes:
      - swetrix-events-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
volumes:
  swetrix-events-data:
    driver: local
